### ISSUE TITLE
Nodegate v2 roadmap

### ISSUE THREAD

**Issue by Shudrum** [weekendesk/nodegate#85]
Hello!

At Weekendesk, we have a huge numbers of routes and many internal feedbacks of the usage of nodegate. We know that some choices made from the beginning must be changed, and long term ideas / improvements needed to be done.

This is why we decided to start the development of the v2.

Here is what we want to achieve:

 - [ ] Replace `request` by `got`.
_Request is now deprecated, and we still didn't want to manage the requests by ourselves, this is why our current candidate is `got`._

 - [ ] Simpler and better URL management.
_At the beginning we wanted full text URL management to allow usage of variables and maybe having an external editor. It just doesn't works well. URLs will only allow parameters declaration, and assigning variables to the parameters, query parameters and body will be done in pure javascript._

 - [ ] New `service` entity.
_Currently all calls are done by writing full URLs, repeating ou (?:micro)services urls, and reusing everywhere many environment variables. This entity will allow to set only one time the URL's domain, and optionnaly hardcode some headers specific to the http calls made to the services, and predefining some requests, for reusing and maintainability._

 - [ ] Some new workers.
_Behind all: `doAsynchronously`, so waited to do asynchronous process, the reason why the container before immutable became mutable._

 - [ ] A log system.
_A real, good, log system, making debugging easier. And I hope with a Chrome extension for._

 - [ ] Workers improvement.
_The workers will have names for debugging, and are going to be directly configurable (instead of a single configuration system like we have).

 - [ ] Simpler request system.
_Allowing workers to reuse it easily._

Stay tuned!
